# Generated by Django 5.0.1 on 2024-03-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
