# Generated by Django 5.0.1 on 2024-01-18 14:22

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('student', 'student'), ('instructure', 'instructure'), ('parent', 'parent')], default='student', max_length=12)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, help_text='e.g Developer etc', max_length=60, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='use format +254...', max_length=13, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=120, null=True, unique=True)),
                ('linkedin', models.URLField(blank=True, max_length=120, null=True, unique=True)),
                ('instagram', models.URLField(blank=True, max_length=120, null=True, unique=True)),
                ('twitter', models.URLField(blank=True, max_length=120, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
