# Generated by Django 5.0.1 on 2024-01-24 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('student', 'student'), ('instructor', 'instructor'), ('parent', 'parent')], default='student', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.location'),
        ),
    ]
